# Generated by Django 3.0.3 on 2020-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproduct',
            name='min_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная масса продукта (гр.)'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='packaging',
            field=models.TextField(choices=[('not known', 'не известно'), ('no packaging', 'без упаковки'), ('paper bag', 'бумажный пакет')], default='не известно', max_length=20, verbose_name='Упаковка'),
        ),
    ]
