# Generated by Django 3.1.7 on 2021-07-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_auto_20210717_2105'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RootProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('name', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('image', models.ImageField(blank=True, max_length=255, upload_to='products', verbose_name='Изображение продукта')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включен')),
                ('description', models.TextField(blank=True, verbose_name='Описание продукта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='FoodProduct',
        ),
    ]
