# Generated by Django 3.2.6 on 2021-08-19 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20210513_2243'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0010_auto_20210819_2120'),
        ('store', '0002_auto_20210717_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('state', models.CharField(choices=[('awaiting_processing', 'В процессе'), ('delivered', 'Доставлено')], default='awaiting_processing', max_length=85, verbose_name='Статус заказа')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='buyer.buyerprofile', verbose_name='Пользователь')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='store.fooddelivery', verbose_name='Доставка')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон'),
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Масса (от покупателя) (гр.)')),
                ('actual_value', models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическая масса (гр.)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='store.foodorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='farmer.farmerproduct', verbose_name='Фермерский продукт')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='foodorder',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='store.location', verbose_name='Адрес'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['delivery', 'buyer', 'location'], name='store_foodo_deliver_7e0ebf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='foodorder',
            unique_together={('delivery', 'buyer', 'location')},
        ),
    ]
