# Generated by Django 4.0.4 on 2022-08-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_deliverycost_historicaldeliverycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Стоимость доставки'),
        ),
    ]
