# Generated by Django 3.0.3 on 2020-06-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200530_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('city_type', models.TextField(choices=[('ctiy', 'город'), ('settlement', 'поселок'), ('деревня', 'village')], default='ctiy', max_length=100, verbose_name='Тип населенного пункта')),
                ('city_value', models.TextField(default='Минск', max_length=200, verbose_name='Населенный пункт')),
                ('city_district', models.TextField(blank=True, choices=[('angarskaya', 'Ангарская'), ('zelonyy_lug', 'Зелёный Луг')], default='', max_length=200, verbose_name='Микрорайон')),
                ('street_type', models.TextField(choices=[('street', 'улица'), ('proezd', 'проезда'), ('avenue', 'проспект'), ('square', 'площадь'), ('side_street', 'переулок'), ('other', 'другое')], default='street', max_length=40, verbose_name='Тип участка города')),
                ('street_value', models.TextField(max_length=300, verbose_name='Название улицы/площади/проезда')),
                ('building', models.TextField(max_length=15, verbose_name='Дом/Строение (с корпусом)')),
                ('sort_key', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('porch', models.TextField(blank=True, default='', max_length=15, verbose_name='Подъезд')),
                ('floor', models.TextField(blank=True, default='', max_length=5, verbose_name='Этаж')),
                ('room', models.TextField(blank=True, default='', max_length=10, verbose_name='Помещение/квартира')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('city_type', models.TextField(choices=[('ctiy', 'город'), ('settlement', 'поселок'), ('деревня', 'village')], default='ctiy', max_length=100, verbose_name='Тип населенного пункта')),
                ('city_value', models.TextField(default='Минск', max_length=200, verbose_name='Населенный пункт')),
                ('city_district', models.TextField(blank=True, choices=[('angarskaya', 'Ангарская'), ('zelonyy_lug', 'Зелёный Луг')], default='', max_length=200, verbose_name='Микрорайон')),
                ('street_type', models.TextField(choices=[('street', 'улица'), ('proezd', 'проезда'), ('avenue', 'проспект'), ('square', 'площадь'), ('side_street', 'переулок'), ('other', 'другое')], default='street', max_length=40, verbose_name='Тип участка города')),
                ('street_value', models.TextField(max_length=300, verbose_name='Название улицы/площади/проезда')),
                ('building', models.TextField(max_length=15, verbose_name='Дом/Строение (с корпусом)')),
                ('sort_key', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('short_name', models.TextField(default='K3V', max_length=8, unique=True, verbose_name='Короткое название')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='packaging',
            field=models.TextField(choices=[('not_known', 'не известно'), ('no_packaging', 'без упаковки'), ('paper_bag', 'бумажный пакет')], default='не известно', max_length=20, verbose_name='Упаковка'),
        ),
    ]
