# Generated by Django 3.0.3 on 2020-06-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200617_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelocation',
            name='building',
            field=models.CharField(max_length=15, verbose_name='Дом/Строение (с корпусом)'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='city_district',
            field=models.CharField(blank=True, choices=[('angarskaya', 'Ангарская'), ('zelonyy_lug', 'Зелёный Луг')], default='', max_length=200, verbose_name='Микрорайон'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='city_type',
            field=models.CharField(choices=[('city', 'город'), ('settlement', 'поселок'), ('деревня', 'village')], default='city', max_length=100, verbose_name='Тип населенного пункта'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='city_value',
            field=models.CharField(default='Минск', max_length=200, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='porch',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='room',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Помещение/квартира'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='street_type',
            field=models.CharField(choices=[('street', 'улица'), ('proezd', 'проезда'), ('avenue', 'проспект'), ('square', 'площадь'), ('side_street', 'переулок'), ('other', 'другое')], default='street', max_length=40, verbose_name='Тип участка города'),
        ),
        migrations.AlterField(
            model_name='homelocation',
            name='street_value',
            field=models.CharField(max_length=300, verbose_name='Название улицы/площади/проезда'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='building',
            field=models.CharField(max_length=15, verbose_name='Дом/Строение (с корпусом)'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='city_district',
            field=models.CharField(blank=True, choices=[('angarskaya', 'Ангарская'), ('zelonyy_lug', 'Зелёный Луг')], default='', max_length=200, verbose_name='Микрорайон'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='city_type',
            field=models.CharField(choices=[('city', 'город'), ('settlement', 'поселок'), ('деревня', 'village')], default='city', max_length=100, verbose_name='Тип населенного пункта'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='city_value',
            field=models.CharField(default='Минск', max_length=200, verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='street_type',
            field=models.CharField(choices=[('street', 'улица'), ('proezd', 'проезда'), ('avenue', 'проспект'), ('square', 'площадь'), ('side_street', 'переулок'), ('other', 'другое')], default='street', max_length=40, verbose_name='Тип участка города'),
        ),
        migrations.AlterField(
            model_name='officelocation',
            name='street_value',
            field=models.CharField(max_length=300, verbose_name='Название улицы/площади/проезда'),
        ),
    ]
