# Generated by Django 3.2.6 on 2021-10-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211025_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой')], default='cash', max_length=100, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='foodorder',
            name='state',
            field=models.CharField(choices=[('created', 'Создан'), ('awaiting_processing', 'Ожидает обработки'), ('delivered', 'Доставлено')], default='created', max_length=85, verbose_name='Статус заказа'),
        ),
    ]
