# Generated by Django 3.0.7 on 2020-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200706_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodhomeorderitem',
            name='actual_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическая масса (г.)'),
        ),
        migrations.AlterField(
            model_name='foodhomeorderitem',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Масса (от покупателя) (г.)'),
        ),
        migrations.AlterField(
            model_name='foodofficeorderitem',
            name='actual_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Фактическая масса (г.)'),
        ),
        migrations.AlterField(
            model_name='foodofficeorderitem',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Масса (от покупателя) (г.)'),
        ),
    ]
