# Generated by Django 3.2.6 on 2021-10-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20211025_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorder',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой')], default='cash', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
