# Generated by Django 3.0.7 on 2020-07-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200713_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodproduct',
            name='min_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная масса продукта (г.)'),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='weight_per_price',
            field=models.CharField(choices=[('1000', '1000 г.'), ('100', '100 г.')], default='1000', max_length=20, verbose_name='Вес за указанную цену'),
        ),
    ]
