# Generated by Django 3.2.6 on 2021-11-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_foodorder_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderitem',
            name='actual_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактическая масса'),
        ),
        migrations.AlterField(
            model_name='foodorderitem',
            name='value',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса (от покупателя)'),
        ),
    ]
