# Generated by Django 3.2.6 on 2021-11-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211122_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderitem',
            name='actual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическая масса'),
        ),
        migrations.AlterField(
            model_name='foodorderitem',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Масса (от покупателя)'),
        ),
    ]
