# Generated by Django 3.2.6 on 2021-12-06 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0017_historicalfarmerproduct'),
        ('store', '0010_auto_20211122_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='farmer.historicalfarmerproduct', verbose_name='Фермерский продукт'),
        ),
    ]
