# Generated by Django 3.2.6 on 2021-12-19 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0012_auto_20211208_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeMargin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('backoffice_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка бэкофиса')),
                ('dev_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка разработчиков')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalTradeMargin',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Изменен')),
                ('backoffice_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка бэкофиса')),
                ('dev_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка разработчиков')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical trade margin',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRootProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Изменен')),
                ('name', models.CharField(max_length=250, verbose_name='Название продукта')),
                ('image', models.TextField(blank=True, max_length=255, verbose_name='Изображение продукта')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Включен')),
                ('description', models.TextField(blank=True, verbose_name='Описание продукта')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.productcategory', verbose_name='Категория')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trade_margin', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.historicaltrademargin', verbose_name='Наценка')),
            ],
            options={
                'verbose_name': 'historical root product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='rootproduct',
            name='trade_margin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_product', to='store.historicaltrademargin', verbose_name='Наценка'),
        ),
    ]
