# Generated by Django 3.2.6 on 2021-12-25 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20211219_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrademargin',
            name='backoffice_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка бэкофиса, %'),
        ),
        migrations.AlterField(
            model_name='historicaltrademargin',
            name='dev_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка разработчиков, %'),
        ),
        migrations.AlterField(
            model_name='rootproduct',
            name='trade_margin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_product', to='store.historicaltrademargin', verbose_name='Наценка'),
        ),
        migrations.AlterField(
            model_name='trademargin',
            name='backoffice_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка бэкофиса, %'),
        ),
        migrations.AlterField(
            model_name='trademargin',
            name='dev_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, verbose_name='Наценка разработчиков, %'),
        ),
    ]
