# Generated by Django 3.0.3 on 2020-05-25 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('location', models.CharField(choices=[('DM3', 'DM3'), ('D104', 'D104'), ('D104A', 'D104A'), ('F25G', 'F25G'), ('KC51A', 'KC51A'), ('K1/1', 'K1/1'), ('K1/2', 'K1/2'), ('K1/5', 'K1/5'), ('K3', 'K3'), ('K3V', 'K3V'), ('N58', 'N58'), ('N177', 'N177'), ('N186', 'N186'), ('P27A', 'P27A'), ('R19A', 'R19A'), ('S15', 'S15'), ('T150', 'T150'), ('Z29', 'Z29')], default='K3V', max_length=8, verbose_name='Офис')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Телефон')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к пользователю')),
                ('tg_username', models.CharField(blank=True, max_length=255, verbose_name='Username в телеграмме')),
                ('user_role', models.CharField(choices=[('buyer', 'Покупатель'), ('supplier', 'Поставщик')], default='buyer', max_length=20, verbose_name='Роль пользователя')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
