# Generated by Django 3.2.6 on 2022-01-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greenuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='greenuser',
            name='last_name',
        ),
    ]
