# Generated by Django 3.1.7 on 2021-05-13 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
