# Generated by Django 3.0.7 on 2020-10-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201026_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_is_verified',
            field=models.BooleanField(default=False, verbose_name='Адрес email подтвержден'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notify_dlvr_create',
            field=models.BooleanField(default=False, verbose_name='Создание новой доставки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notify_dlvr_status',
            field=models.BooleanField(default=False, verbose_name='Изменение статуса доставки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tg_is_connected',
            field=models.BooleanField(default=False, verbose_name='Подключен пользователь Telegram'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tg_notify_dlvr_create',
            field=models.BooleanField(default=False, verbose_name='Создание новой доставки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tg_notify_dlvr_status',
            field=models.BooleanField(default=False, verbose_name='Изменение статуса доставки'),
        ),
    ]
