# Generated by Django 3.1.7 on 2021-05-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerprofile',
            old_name='tg_name',
            new_name='name',
        ),
    ]
