# Generated by Django 3.1.7 on 2021-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_auto_20210513_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
