# Generated by Django 3.2.6 on 2021-08-31 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210819_2120'),
        ('buyer', '0003_auto_20210513_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='region',
            field=models.CharField(blank=True, max_length=255, verbose_name='Регион'),
        ),
        migrations.CreateModel(
            name='BuyerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('value', models.DecimalField(decimal_places=2, help_text="'+': проект должен покупателю, '-': покупатель должен проекту)", max_digits=9, verbose_name='Значение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_balance', to='store.foodorder', verbose_name='Заказ')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
