# Generated by Django 3.2.6 on 2021-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_auto_20210831_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerbalance',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text="'+': проект должен покупателю, '-': покупатель должен проекту", max_digits=9, verbose_name='Значение'),
        ),
    ]
