# Generated by Django 3.2.6 on 2021-11-06 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_foodorder_payment_type'),
        ('buyer', '0007_alter_buyerbalance_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerbalance',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_balance', to='store.foodorderitem', verbose_name='Заказ'),
        ),
    ]
