# Generated by Django 3.2.6 on 2022-01-03 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('feedback', models.TextField(blank=True, default='', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзывы на фермера',
                'verbose_name_plural': 'Отзывы на фермеров',
            },
        ),
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('value', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Объем/Кол./Вес')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('gm', 'гр.'), ('pс', 'шт.'), ('L.', 'л')], default='kg', max_length=2, verbose_name='Ед. измерения')),
                ('size', models.CharField(choices=[('s', 'Маленький'), ('M', 'Средний'), ('L', 'Большой')], default='M', max_length=1, verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('photo', models.ImageField(blank=True, max_length=255, upload_to='profile_photos', verbose_name='Фото')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('service_zone', models.TextField(blank=True, default='', verbose_name='Зона обслуживания')),
                ('legal_name', models.CharField(blank=True, default='', max_length=500, verbose_name='Название компании / фермерского хозяйства')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalFarmerProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Изменен')),
                ('value', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Объем/Кол./Вес')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('gm', 'гр.'), ('pс', 'шт.'), ('L.', 'л')], default='kg', max_length=2, verbose_name='Ед. измерения')),
                ('size', models.CharField(choices=[('s', 'Маленький'), ('M', 'Средний'), ('L', 'Большой')], default='M', max_length=1, verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('farmer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farmer.farmerprofile', verbose_name='Фермер')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical farmer product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
