# Generated by Django 3.2.6 on 2022-01-03 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfarmerproduct',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.rootproduct', verbose_name='Базовый продукт'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_farmerprofile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerprofile', verbose_name='Фермер'),
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_product', to='store.rootproduct', verbose_name='Базовый продукт'),
        ),
        migrations.AddField(
            model_name='farmerfeedback',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_feedback', to='store.foodorderitem'),
        ),
    ]
