# Generated by Django 4.0.4 on 2022-10-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_alter_farmerprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gm', 'гр.'), ('pс', 'шт.'), ('L.', 'л'), ('p.', 'порция')], default='kg', max_length=2, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='historicalfarmerproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gm', 'гр.'), ('pс', 'шт.'), ('L.', 'л'), ('p.', 'порция')], default='kg', max_length=2, verbose_name='Ед. измерения'),
        ),
    ]
