# Generated by Django 3.1.7 on 2021-06-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_auto_20210513_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название компании / фермерского хозяйства'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='service_zone',
            field=models.TextField(blank=True, default='', verbose_name='Зона обслуживания'),
        ),
    ]
