# Generated by Django 3.1.7 on 2021-07-08 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
        ('farmer', '0004_auto_20210617_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('gm', 'гр.'), ('pс', 'шт.'), ('L.', 'л')], max_length=2, verbose_name='Ед. измерения')),
                ('size', models.CharField(choices=[('s', 'Маленький'), ('M', 'Средний'), ('L', 'Большой')], max_length=1, verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Фермер')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.foodproduct', verbose_name='Название продукта')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
