# Generated by Django 3.1.7 on 2021-07-17 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_farmerproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='farmerproduct',
            name='weight',
        ),
    ]
