# Generated by Django 3.1.7 on 2021-07-15 20:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_auto_20210513_2243'),
        ('farmer', '0005_farmerproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer.buyerprofile')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerprofile')),
            ],
            options={
                'verbose_name': 'Рейтинг фермера',
                'verbose_name_plural': 'Рейтинги фермеров',
            },
        ),
    ]
