# Generated by Django 3.1.7 on 2021-07-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210717_2105'),
        ('farmer', '0006_auto_20210717_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.rootproduct', verbose_name='Базовый продукт'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerproduct',
            name='value',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10, verbose_name='Объем/Количество/Вес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='size',
            field=models.CharField(choices=[('s', 'Маленький'), ('M', 'Средний'), ('L', 'Большой')], default='M', max_length=1, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'кг'), ('gm', 'гр.'), ('pс', 'шт.'), ('L.', 'л')], default='kg', max_length=2, verbose_name='Ед. измерения'),
        ),
    ]
