# Generated by Django 3.1.7 on 2021-07-17 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_auto_20210717_2105'),
        ('farmer', '0006_farmerrating'),
    ]

    operations = [
    ]
