# Generated by Django 3.1.7 on 2021-08-17 18:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_merge_20210718_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerrating',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerrating',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerprofile', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='farmerproduct',
            name='value',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Объем/Кол./Вес'),
        ),
    ]
