# Generated by Django 3.2.6 on 2021-08-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210819_2120'),
        ('farmer', '0010_auto_20210819_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerfeedback',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_feedback', to='store.foodorderitem'),
        ),
    ]
