# Generated by Django 3.2.6 on 2021-08-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_farmerfeedback_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerfeedback',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='Отзыв'),
        ),
    ]
