# Generated by Django 3.2.6 on 2021-08-19 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210819_2120'),
        ('farmer', '0012_alter_farmerfeedback_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerfeedback',
            name='farmer',
        ),
        migrations.AlterField(
            model_name='farmerfeedback',
            name='order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_feedback', to='store.foodorderitem'),
        ),
    ]
