# Generated by Django 3.2.6 on 2021-09-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_rootproduct_category'),
        ('farmer', '0013_auto_20210819_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_product', to='store.rootproduct', verbose_name='Базовый продукт'),
        ),
    ]
