# Generated by Django 3.2.6 on 2021-10-28 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0015_alter_farmerfeedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerfeedback',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
