# Generated by Django 3.2.6 on 2021-12-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0010_auto_20211122_1851'),
        ('farmer', '0016_alter_farmerfeedback_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFarmerProduct',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(blank=True, editable=False, verbose_name='Изменен')),
                ('value', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Объем/Кол./Вес')),
                ('unit', models.CharField(choices=[('kg', 'кг'), ('gm', 'гр.'), ('pс', 'шт.'), ('L.', 'л')], default='kg', max_length=2, verbose_name='Ед. измерения')),
                ('size', models.CharField(choices=[('s', 'Маленький'), ('M', 'Средний'), ('L', 'Большой')], default='M', max_length=1, verbose_name='Размер')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('farmer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='farmer.farmerprofile', verbose_name='Фермер')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='store.rootproduct', verbose_name='Базовый продукт')),
            ],
            options={
                'verbose_name': 'historical farmer product',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
